### ISSUE TITLE
Entity ID changes

### ISSUE THREAD

**Issue by flopp999** [toreamun/amshan-homeassistant#56]
After a restart of HA I sometimes get different Entity ID.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/21694965/209633361-8788550d-aa9b-4181-913e-8ce2530fc61a.png">

After a restart it will fix itself
<img width="255" alt="image" src="https://user-images.githubusercontent.com/21694965/209634348-c95a8cef-7d09-4b42-ae60-fff21c0c4998.png">

```yaml


{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.12.8",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Stockholm",
    "os_name": "Linux",
    "os_version": "5.15.80",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.29.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "amshan": {
      "version": "2022.10.2",
      "requirements": [
        "amshan[serial]==2.0.5"
      ]
    }
  },
  "integration_manifest": {
    "domain": "amshan",
    "name": "AMS HAN meter",
    "version": "2022.10.2",
    "config_flow": true,
    "documentation": "https://github.com/toreamun/amshan-homeassistant",
    "issue_tracker": "https://github.com/toreamun/amshan-homeassistant/issues",
    "codeowners": [
      "@toreamun"
    ],
    "requirements": [
      "amshan[serial]==2.0.5"
    ],
    "after_dependencies": [
      "mqtt"
    ],
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "config_entry": {
      "entry_id": "81aaaaa1bxxxf12936bbb1e0000f5250",
      "version": 3,
      "domain": "amshan",
      "title": "Elm\u00e4taren",
      "data": {
        "connection_type": "hass_mqtt",
        "connection": {
          "mqtt_topics": "Elmataren/+"
        }
      },
      "options": {
        "scale_factor": 1.0
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    }
  }
}
```
